### Load in NumPy (remember to pip install numpy first)

In [2]:
import numpy as np

### The Basics

In [9]:
a = np.array([1,2,3]) # This will allow us to specific the type in which the value are store in the numpy arrays
# a = np.array([1,2,3], dtype='int32') # This will allow us to specific the type in which the value are store in the numpy arrays
print(a)
b = np.array([2,3,4])
print(b)

[1 2 3]
[2 3 4]


In [5]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)
b1 = np.array([[9.1,8.1,7.1],[6.1,5.1,4.1]])
print(b1)

[[9. 8. 7.]
 [6. 5. 4.]]
[[9.1 8.1 7.1]
 [6.1 5.1 4.1]]


In [6]:
# Get Dimension
# a.ndim
# b.ndim
b1.ndim

2

In [18]:
# Get Shape - Row and columns
b.shape

(2, 3)

In [10]:
# Get Type and size
a.dtype

dtype('int64')

In [11]:
# Get Size
a.itemsize

8

In [12]:
# Get total size
a.nbytes

24

In [35]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [22]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]]) # This is a two dimension array. 
print(a)
a1 = np.array([[9,8,7,6,5,4],[1,2,3,4,5,6]])
print(a1.shape) # This will return the dimension of the array. Where the first element is the row and second element is the column number.
print(type(a1.shape)) # The type of shape is a tuple.
print(a1)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 6)
<class 'tuple'>
[[9 8 7 6 5 4]
 [1 2 3 4 5 6]]


In [23]:
# Get a specific element [r, c] # Python indexing starts at row 0. 
a1[1, 5] # row number 1,and column number 5.

6

In [27]:
# Get a specific row
# a[0, :] # For selecting the single row (first row), and all columns
a1[0,:-1] # For selecting the single row (first row), and one column less.

array([9, 8, 7, 6, 5])

In [32]:
# Get a specific column
# a[:, 2]
a1[:, 2]

array([7, 3])

In [33]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2] # This will select the first row 0, and starting at index 1 which is the second column, -1 which is the last column which is not inclusive, so it will be last but one, and step size of 2 which means that, it will be alternate columns.

array([2, 4, 6])

In [38]:
print(a1) 
print(a1[1,5])
a1[1,5] = 200 # This is change the element at row 1, and column 5 
print(a1)

a[:,2] = [1,2]
print(a)

[[ 9  8  7  6  5  4]
 [ 1  2  3  4  5 20]]
20
[[  9   8   7   6   5   4]
 [  1   2   3   4   5 200]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [4]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
# Get specific element (work outside in)
b[0,1,1]

9

In [11]:
# replace 
b[:,1,:] = [[9,9],[8,8]]

In [12]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [13]:
# All 0s matrix
np.zeros((2,3)) # This is two rows and three columns 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# All 1s matrix
np.ones((4,2,2), dtype='int32') # This is 4 rows, 2 columns, and third dimension.  

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [44]:
# Any other number - This will populate a 2 X 2 matrix with 99 as the value.
np.full((2,2), 99)

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [49]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [56]:
# Random decimal numbers
np.random.rand(4,2) # 4 rows and 2 columns

array([[0.07805642, 0.53385716],
       [0.02494273, 0.99955252],
       [0.48588042, 0.91247437],
       [0.27779213, 0.16597751]])

In [3]:
# Random Integer values
np.random.randint(-4,8, size=(3,3)) # This is 3 X 3 Matrix using numbers from -4, till 8.

array([[-4, -3,  7],
       [ 5, -3,  7],
       [-2, -1,  6]])

In [76]:
# The identity matrix
np.identity(5) # By nature will be a square metrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
# Repeat an array
arr = np.array([[1,2,3]]) # This is a two dimensional array
r1 = np.repeat(arr,3, axis=0)  # axis= 0 mean along the rows
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [7]:
output = np.ones((5,5)) # This will make everything one
print(output)

z = np.zeros((3,3)) # This will print a 3 X 3 matrix of zeros,  
z[1,1] = 9 # This will replace the (1,1) in the 3X3 matrix position value with 9
print(z)

output[1:-1,1:-1] = z # Here we are replacing the first row to last row, where last row not included, and columns starting from column 1 to last column where last column not included.
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [98]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


### Mathematics

In [111]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [109]:
a + 2

array([5, 6, 7, 8])

In [102]:
a - 2

array([-1,  0,  1,  2])

In [103]:
a * 2

array([2, 4, 6, 8])

In [104]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [118]:
b = np.array([1,0,1,0])
a + b

array([1, 0, 3, 0])

In [113]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [116]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [117]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [127]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [132]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [133]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [134]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [139]:
np.min(stats)

1

In [141]:
np.max(stats, axis=1)

array([3, 6])

In [143]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [151]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [158]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [164]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [179]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [196]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])